//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNKORE.UI.WinForms.Styler.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iNKORE.UI.WinForms.Styler.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Common Controls library version 6.0 not loaded. Must run on Vista and must provide a manifest. 的本地化字符串。
        /// </summary>
        internal static string CommonControlEntryPointNotFound {
            get {
                return ResourceManager.GetString("CommonControlEntryPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop composition is not enabled. 的本地化字符串。
        /// </summary>
        internal static string DwmNotEnabled {
            get {
                return ResourceManager.GetString("DwmNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop composition is not supported by operating system. 的本地化字符串。
        /// </summary>
        internal static string DwmOsNotSupported {
            get {
                return ResourceManager.GetString("DwmOsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get thumbnail&apos;s original size. 的本地化字符串。
        /// </summary>
        internal static string DwmThumbnailQueryFailure {
            get {
                return ResourceManager.GetString("DwmThumbnailQueryFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to update thumbnail properties. 的本地化字符串。
        /// </summary>
        internal static string DwmThumbnailUpdateFailure {
            get {
                return ResourceManager.GetString("DwmThumbnailUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source and target windows cannot be the same. 的本地化字符串。
        /// </summary>
        internal static string DwmWindowMatch {
            get {
                return ResourceManager.GetString("DwmWindowMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native call to {0} failed. 的本地化字符串。
        /// </summary>
        internal static string NativeCallFailure {
            get {
                return ResourceManager.GetString("NativeCallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create TaskDialog. 的本地化字符串。
        /// </summary>
        internal static string TaskDialogFailure {
            get {
                return ResourceManager.GetString("TaskDialogFailure", resourceCulture);
            }
        }
    }
}
